### ISSUE TITLE
Publish documentation as Dash docset

### ISSUE THREAD

**Issue by brejoc** [intercoolerjs/intercooler-js#192]
I'm a heavy [Zeal](https://zealdocs.org/) user, which is a [Dash](https://kapeli.com/dash) clone. Zeal/Dash lets you browse and search docs offline.

I have found a [Docset Generation Guide](https://kapeli.com/docsets), but haven't looked any further yet. Perhaps it would be possible to easily generate a docset for Zeal/Dash with minimum effort.

**Comment by brejoc** [comment]
Just wanted to let you know, that I've managed to create a docset based on the HTML docs.

![auswahl_655](https://cloud.githubusercontent.com/assets/34246/24567520/699e6d82-165e-11e7-8b3f-11a5d4919c49.png)

This needs some polishing and I have to look into the available data types. Also the styling is broken at the moment.

**Comment by carsongross** [comment]
Awesome!

Are there any changes I should make to the structure to make this easier?


On March 31, 2017 at 1:11:50 PM, Jochen Breuer (notifications@github.com)
wrote:

Just wanted to let you know, that I've managed to create a docset based on
the HTML docs.

[image: auswahl_655]
<https://cloud.githubusercontent.com/assets/34246/24567520/699e6d82-165e-11e7-8b3f-11a5d4919c49.png>

This needs some polishing and I have to look into the available data types.
Also the styling is broken at the moment.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LeadDyno/intercooler-js/issues/192#issuecomment-290817150>,
or mute the thread

**Comment by brejoc** [comment]
@carsongross Sorry, I've been a bit busy lately. I'm trying to keep the structure as is and I think that should be possible.

**Comment by carsongross** [comment]
Jochen, should I keep this open?

**Comment by brejoc** [comment]
@carsongross I know, I'm dragging my feet. Yes, please leave it open. I'm trying to polish it this week!
