### ISSUE TITLE
Double Post on Ajax Request

### ISSUE THREAD

**Issue by rubahjantan** [intercoolerjs/intercooler-js#200]
I have form called via ajax using intercoolerjs, when i click submit button it send POST request twice. can i add something like e.preventDefault or e.stopPropagation similiar to when i using jQuery?
Thank you.

**Comment by carsongross** [comment]
Can you post the relevant HTML?

A form with intercooler attributes on it should not submit twice.


On May 9, 2017 at 11:53:13 PM, rubahjantan (notifications@github.com) wrote:

I have form called via ajax using intercoolerjs, when i click submit button
it send POST request twice. can i add something like e.preventDefault or
e.stopPropagation when i using jQuery?
Thank you.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LeadDyno/intercooler-js/issues/200>, or mute the thread

**Comment by rubahjantan** [comment]
this is form called via ajax using intecooler, 
<div class="rmutasi-form">
    <div class="row">
    `<form` id="rmutasi-form" action="/sipo2/web/index.php?r=konfirmasi/create" ic-target="#konfirmasi-r-mutasi" ic-verb="POST" ic-src="/sipo2/web/index.php?r=konfirmasi/create" ic-trigger-on="default" ic-deps="ignore">
		>
 </form>
    </div>    
    <div class="row">
    <button type="submit" class="btn btn-primary"> Save</button>
    </div>
</div>

**Comment by carsongross** [comment]
Can you remove the action attribute and see if  that works?

**Comment by rubahjantan** [comment]
I have omitted the action attribute, but there is a strange behavior, sometimes sent once twice sometimes. I will check my code first, because I use the yii framework

**Comment by rubahjantan** [comment]
I do not know what actually happened, I have added attribute ic-trigger-on and manually trigger it on button submit, and this works.

**Comment by jlahijani** [comment]
This occurs when I put ic-post-to on a 'label' element, but doesn't occur when on an 'a' element.

**Comment by jlahijani** [comment]
Actually, nevermind.  When properly putting the "for" attribute on the label, it works fine.

**Comment by shehjart** [comment]
Running into the same problem resulting in 2 db entries on  form submit.

Using version 1.2.1.

<form id="createentry" ic-post-to="/createentry"  
                        ic-on-error = "handle_create_entry_error"       
                        ic-target = "#entrylist">                             
                            {% csrf_token %}                                    
                            <input id="requesttype" type="hidden"               
                            name="requesttype" value="createentryerror"></input>
                            <div class="input-field">                           
                                <input id="entryname" name="entryname" maxlength=50 type="text">
                                <label for="entryname">New Entry Name</label> 
                            </div>                                              
                            <br>                                                
                            <div class="error" id="error-msg"></div>            
                            <button class="btn waves-effect waves-light"        
                            onclick="return send_create_entry_request ();">Create</button>
                        </form>

Could this be because send_create_entry_request calls Intercooler.triggerRequest?

**Comment by jonfulk** [comment]
This seems to be related to the issue described here: https://github.com/LeadDyno/intercooler-js/issues/222

I'm seeing multiple events firing on elements loaded by Intercooler.

**Comment by carsongross** [comment]
@jonfulk can you give me some example HTML for your intercooler?

**Comment by carsongross** [comment]
@shehjart can you explain what this means:

> Could this be because send_create_entry_request calls Intercooler.triggerRequest?

**Comment by shehjart** [comment]
I fixed the problem.

I was calling Intercooler.triggerRequest inside the form's onclick method.

function send_create_entry_request() {
Intercooler.triggerRequest
}

For some reason, this sequence was POSTing twice. WHen i added a return false after triggerRequest, it started posting only once.

**Comment by jonfulk** [comment]
@carsongross I've used your suggestion in #222 to use `Intercooler.ready(function(elt) { ... });` and then `elt.find( ... )` for the handler, however, I can't figure out how to get that solution work on a handler listening for a `keydown` event on the body. For example, I want to submit a form using `metaKey + enter`, but the form is loaded via an Intercooler request, so I put my handler in the `Intercooler.ready()`. It looks something like this: 
```   $('body').keydown(function(e) {
    if (e.ctrlKey || e.metaKey) {
      console.log('cmd pressed');
      if (e.key === "Enter") {
        console.log('cmd + enter pressed');
        var $form = $('#desk-form');
        $form.submit();
        return false;
      }
    }
  });```

Since I'm using `ic-poll` on this page, Intercooler keeps adding the same handlers to the page. The `console.log`s are there to show that each key press fires for each time that Intercooler has been loaded into the page.

Similarly, for each poll, the polled requests accumulate an additional poll for each load of Intercooler. In other words, if I've been sitting there long enough for it to poll 4 times, there will be 4 requests made for each route that is being polled. I think this has to do with the fact that I'm using some custom js to to add a request header on `beforeSend`, and since this is inside the `Intercooler.ready()`, it keeps accumulating for each reload.

At this point, it looks like I'm going to have to use `stopImmediatePropatation()` on any handlers that are loaded by Intercooler, acting on something loaded by Intercooler (such as a form or request), yet listening for an event that is higher up in the DOM than the loaded element (such as a keydown on the body). Do you know of a better way to approach that?

**Comment by carsongross** [comment]
Hi jon,

the issue is that you are putting the keydown handler on the body every single time an intercooler request loads.  Since the body is a stable element (assuming you are targeting a div within the body) then you are going to get multiple handlers on that body, causing the duplicate submissions.

This logic should be in a plain old jQuery onLoad handler, IMO.  Sorry it's a little annoying you have to make a distinction between the two, but it makes sense if you think about what intercooler is doing functionally.
