### ISSUE TITLE
Allow customization of 'disable' class during ajax request

### ISSUE THREAD

**Issue by msurdi** [intercoolerjs/intercooler-js#211]
It would be nice to be able to customize the default 'disabled' class that is automatically added to elements when a request is in-flight, that is, change the name of the class added, or maybe even be able to turn off this feature.

I'm having a weird ui behavior where after clicking in a checkbox the cursor blinks and it's because bootstrap's disabled class sets `cursor: not-allowed` for the `disabled` class

**Comment by carsongross** [comment]
Hi Matias,

I will look into something like this.

In the meantime you can probably override the bootstrap behavior using an
!important CSS rule:

https://css-tricks.com/when-using-important-is-the-right-choice/

Cheers,
Carson


On July 1, 2017 at 9:05:20 AM, Matias Surdi (notifications@github.com)
wrote:

It would be nice to be able to customize the default 'disabled' class that
is automatically added to elements when a request is in-flight, that is,
change the name of the class added, or maybe even be able to turn off this
feature.

I'm having a weird ui behavior where after clicking in a checkbox the
cursor blinks and it's because bootstrap's disabled class sets cursor:
not-allowed for the disabled class

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LeadDyno/intercooler-js/issues/211>, or mute the thread

**Comment by msurdi** [comment]
Yes, that's the workaround I'm already using. I could send you a PR with this feature if you want, just let me know the general approach you would like me to follow for ir if so.
