### ISSUE TITLE
Should there be a version of X-IC-Script that executes after the element is replaced?

### ISSUE THREAD

**Issue by esb** [intercoolerjs/intercooler-js#293]
I've been trying to find a way to re-bind an element after it has been updated by Intercooler. The element is tagged using another package, but I need to re-bind it once it's been updated to restore the functionality.

I can include JS in the partial processed by Intercooler, but I run into problems when executing it during the initial page load. I found the X-IC-Script response header and thought this would be a good way to execute the re-bind code after the page has been updated.

However, it turns out that X-IC-Script is executed BEFORE the page is updated. How useful is this? Would it be possible to provide an alternative version that runs after the page update?

**Comment by scsmash3r** [comment]
> I've been trying to find a way to re-bind an element after it has been updated by Intercooler. The element is tagged using another package, but I need to re-bind it once it's been updated to restore the functionality.
> 
> I can include JS in the partial processed by Intercooler, but I run into problems when executing it during the initial page load. I found the X-IC-Script response header and thought this would be a good way to execute the re-bind code after the page has been updated.
> 
> However, it turns out that X-IC-Script is executed BEFORE the page is updated. How useful is this? Would it be possible to provide an alternative version that runs after the page update?

Since swapping and re-binding takes some milliseconds to apply, you probably will need to use `setTimeout` after headers are processed or when Intercooler is ready. You can do like this:

```
Intercooler.ready(function() {
  setTimeout(function() {
    yourReloadFunc();
  }, 25);
});
```

... or give your `X-IC-Script` executing function some timeout. `X-IC-Script` executes when response headers are parsed, but there is no guarantee that old content was swapped by new and Intercooler is ready on a new content. So that's why you need that tiny delay. At least that's how I manage to handle such cases as you described.

Quoting developer's word from gitter:

> We have a 20 millisecond delay after the completion of the request before we do the swap. IIRC this was to allow CSS transitions to function correctly.

**Comment by esb** [comment]
Ah, excellent! The Intercooler.ready function solves the problem nicely. Thanks for the feedback.
